import math
import re
import torch

# Decode extended token ids to text, preserving the special markup tokens.
SPECIAL_TOKENS_MAP = {
    256: "<think>", 257: "</think>",
    258: "<|ref|>", 259: "</|ref|>",
    260: "<|box|>", 261: "</|box|>",
    262: "<|point|>", 263: "</|point|>",
    264: "<call>", 265: "</call>",
    266: "<resp>", 267: "</resp>",
}
PAD_ID = 268
VOCAB_SIZE = 269


def decode_byte_trajectory(token_ids):
    """Render a list of extended token ids into a string for regex scoring."""
    chars = []
    for tid in token_ids:
        tid = int(tid)
        if tid in SPECIAL_TOKENS_MAP:
            chars.append(SPECIAL_TOKENS_MAP[tid])
        elif 0 <= tid <= 255:
            try:
                chars.append(chr(tid))
            except ValueError:
                pass
        # 268 (pad) and any other id are dropped.
    return "".join(chars)


class VisualPrimitivesRewardEngine:
    """Deterministic, NaN-safe reward rules for generated byte trajectories.

    Three independent signals (Format / Quality / Accuracy) replace a heavy
    external LLM judge so GRPO stays on a single 16GB GPU.
    """

    def __init__(self, alpha=0.7, beta=3.0):
        self.alpha = alpha
        self.beta = beta

    def compute_format_reward(self, text_output):
        """Syntax validity of the markup tags + loop-protection."""
        reward = 1.0
        if "<think>" in text_output and "</think>" not in text_output:
            reward -= 0.3
        if text_output.count("<think>") != text_output.count("</think>"):
            reward -= 0.2
        ref_count = text_output.count("<|ref|>")
        box_count = text_output.count("<|box|>")
        point_count = text_output.count("<|point|>")
        if ref_count != (box_count + point_count):
            reward -= 0.3
        boxes = re.findall(r"\[\[.*?\]\]", text_output)
        if len(boxes) != len(set(boxes)) and len(boxes) > 0:
            reward -= 0.5  # hard penalty for repeating the same coordinates
        return max(0.0, reward)

    def compute_quality_reward(self, text_output):
        """Depth of the reasoning chain (anti-laziness / anti-overthink)."""
        reward = 1.0
        think_content = re.findall(r"<think>(.*?)</think>", text_output, re.DOTALL)
        if not think_content:
            return 0.0
        think_len = len(think_content[0].strip())
        if think_len < 10:
            reward -= 0.5
        elif think_len > 1500:
            reward -= 0.2
        return max(0.0, reward)

    def compute_accuracy_counting(self, text_output, ground_truth_count):
        """Exponential decay reward for exact counting (DeepSeek formula).

        R = alpha * exp(-beta * |pred - gt| / (gt + 1))
        """
        if "</think>" not in text_output:
            return 0.0
        numbers = re.findall(r"\d+", text_output.split("</think>")[-1])
        if not numbers:
            return 0.0
        try:
            pred_val = float(numbers[-1])
        except (ValueError, IndexError):
            return 0.0
        gt_val = float(ground_truth_count)
        relative_error = abs(pred_val - gt_val) / (gt_val + 1.0)
        return self.alpha * math.exp(-self.beta * relative_error)

    def compute_accuracy_maze(self, text_output, ground_truth_path_coords):
        """Maze reachability with causal truncation on the first wrong step."""
        points_str = re.findall(r"<\|point\|>\[\[(.*?)\]\]", text_output)
        if not points_str:
            return 0.0
        pred_coords = []
        for p in points_str:
            try:
                coords = [int(c) for c in p.split(",")]
                if len(coords) == 2:
                    pred_coords.append(coords)
            except ValueError:
                pass
        if not pred_coords:
            return 0.0
        correct_steps = 0
        for i, pt in enumerate(pred_coords):
            if i >= len(ground_truth_path_coords):
                break
            if pt == ground_truth_path_coords[i]:
                correct_steps += 1
            else:
                break  # causal truncation: first error ends the path
        return correct_steps / len(ground_truth_path_coords)
